services:
  mariadb-server:
    image: mariadb:11
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${SERVER_HOST_PASSWORD}
      MARIADB_DATABASE: ${DB_FILE}
      MARIADB_USER: ${DB_GAME_USER}
      MARIADB_PASSWORD: ${DB_GAME_USER_PWD}
    volumes:
    #  - mariadb_volume:./game:/game
      - ./game:/game:ro
    networks:
      - mariadb_network
    ports:
     - "${DB_PORT}:3306"

volumes:
  mariadb_volume:

networks:
  mariadb_network:
